require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - 'phrase.gemspec'

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false
